### ISSUE TITLE
Overview input css destroyed my printing page

### ISSUE THREAD

**Issue by jerrylee17** [SCE-Development/Core-v4#194]
change src/Pages/Overview/Overview.css to use classes/id's instead of changing all the inputs.  The issue can be found in [this file](https://github.com/SCE-Development/Core-v4/blob/c8aa745cc4702201f1d7e8bb9fce818e36f04ce8/src/Pages/Overview/Overview.css#L65)

```css
input, select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0px;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  font-size: 16px;
  initial-letter-align: left
}
```
